### ISSUE TITLE
Publish Lab Website (+homepage)

### ISSUE THREAD

**Issue by Blayzeing** [ManganLab/common#13]

**Comment by michaelmangan** [comment]
Issue here - although I get access to the Google Sites via our university log-in, the functionality to publish a page is restricted ....... GRRRR!

I suggest we migrate into a Github Pages site which will then be a one-stop-shop for all of our code, webpage and data.

**Comment by michaelmangan** [comment]
So we now have our first version of an organisation GitHub Page and also I have created a personal page.  I need to add instructions to the lab wiki on how to set up and link personal pages.  Also I want to research the use of projects and project pages in Github

**Comment by Blayzeing** [comment]
Just as a note, I had a look around last Friday at setting up multiple pages, but I don't think GitHub pages supports that without using Jekyll locally.
